[package]
name = "fraust-echo"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
alsa = "0.1.0"
libc = "0.2.8"
tinyosc = "0.0.3"

[build-dependencies]
gcc = "0.3"

