[package]
name = "fraust-echo"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
portaudio = "0.6.2"
libc = "0.2.0"
tinyosc = "0.0.2"

[build-dependencies]
gcc = "0.3"

