[package]
name = "fraust-echo"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
clap = "2.20.5"
tinyosc = "0.0.3"
portaudio-rs = "0.3.2"

[build-dependencies]
gcc = "0.3"

