[package]
name = "fraust-echo"
version = "0.1.0"
authors = ["Ben B <bburdette@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
tinyosc = "0.0.2"
portaudio       = { git = "https://github.com/mvdnes/portaudio-rs" }

[build-dependencies]
gcc = "0.3"

